// <auto-generated />
namespace WebTH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deletestartdatepromotion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletestartdatepromotion));
        
        string IMigrationMetadata.Id
        {
            get { return "202505130254077_deletestartdatepromotion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
